package services

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"edi/internal/db"
	"edi/internal/models"
)

// Agent suggestions are generated by the user's own ChatGPT model (see openai.go).
// AI features require a connected OpenAI account — there is no offline fallback.

// ListSuggestions returns suggestions, optionally filtered by status.
func (s *Service) ListSuggestions(status string) ([]models.AgentSuggestion, error) {
	out, err := s.store.ListSuggestions(s.userID, status)
	return orEmpty(out), err
}

// llmSuggestion is the strict JSON shape we ask the model to return.
type llmSuggestion struct {
	Type           string `json:"type"`
	Title          string `json:"title"`
	Reason         string `json:"reason"`
	SuggestedQuest struct {
		Title            string           `json:"title"`
		Description      string           `json:"description"`
		Type             string           `json:"type"`
		Difficulty       string           `json:"difficulty"`
		AttributeRewards map[string]int64 `json:"attribute_rewards"`
	} `json:"suggested_quest"`
}

// GenerateSuggestions asks the connected ChatGPT model to analyze the user's
// current state and propose 2-4 tailored quests, then persists them as pending.
// Requires a connected OpenAI account (returns ErrOpenAINotConnected otherwise).
func (s *Service) GenerateSuggestions() ([]models.AgentSuggestion, error) {
	prompt, err := s.buildSuggestionPrompt()
	if err != nil {
		return nil, err
	}

	raw, err := s.completeWithOpenAI(suggestionInstructions, prompt)
	if err != nil {
		return nil, err // includes ErrOpenAINotConnected
	}

	var parsed struct {
		Suggestions []llmSuggestion `json:"suggestions"`
	}
	if err := json.Unmarshal([]byte(extractJSONObject(raw)), &parsed); err != nil {
		return nil, fmt.Errorf("%w: the model returned an unexpected response, try again", ErrValidation)
	}

	// A fresh generation replaces the current pending set.
	if err := s.store.DeletePendingSuggestions(s.userID); err != nil {
		return nil, err
	}

	for _, ls := range parsed.Suggestions {
		in := models.QuestInput{
			Title:            strings.TrimSpace(ls.SuggestedQuest.Title),
			Description:      strings.TrimSpace(ls.SuggestedQuest.Description),
			Type:             ls.SuggestedQuest.Type,
			Difficulty:       ls.SuggestedQuest.Difficulty,
			AttributeRewards: ls.SuggestedQuest.AttributeRewards,
		}
		if err := s.validateQuestInput(&in); err != nil {
			continue // skip anything the model got wrong rather than fail the batch
		}
		sug := models.AgentSuggestion{
			Type:           orFallback(ls.Type, "suggestion"),
			Title:          strings.TrimSpace(ls.Title),
			Reason:         strings.TrimSpace(ls.Reason),
			SuggestedQuest: in,
		}
		if sug.Title == "" {
			sug.Title = in.Title
		}
		if _, err := s.store.InsertSuggestion(s.userID, sug); err != nil {
			return nil, err
		}
	}

	out, err := s.store.ListSuggestions(s.userID, "pending")
	return orEmpty(out), err
}

const suggestionInstructions = `You are the in-game coach for "edi", a life-RPG habit app. The user completes ` +
	`real-life "quests" that award XP to nine attributes (strength, discipline, focus, health, wealth, ` +
	`relationships, learning, creativity, spirituality), which level up. Suggest concrete, motivating next ` +
	`quests tailored to their current state. Be specific and encouraging, never generic; the reason must ` +
	`cite a real number or detail from their data.

Respond with ONLY a JSON object, no prose or markdown fences, matching exactly:
{"suggestions":[{"type":"string short slug","title":"string","reason":"one motivating sentence referencing their data","suggested_quest":{"title":"string","description":"string","type":"daily|weekly|main|side|boss|recovery","difficulty":"trivial|easy|medium|hard|boss","attribute_rewards":{"<attribute_key>":<integer 5-100>}}}]}

Rules:
- Return 3 to 4 suggestions. attribute_rewards keys MUST be from the nine attribute keys above.
- Do NOT duplicate or closely overlap any of the user's ACTIVE quests listed in the input — propose genuinely new, distinct actions (a different activity, not a reworded version of one they already have).
- Make the batch VARIED: mix quest types AND difficulties. Cover more than one theme — don't propose two similar quests. At most ONE recovery quest, and only when energy is low or activity is high (never if recovery quests are already active).
- Include at least one AMBITIOUS quest (difficulty medium/hard/boss, type main/side/boss) that builds on a STRENGTH the user is already crushing — a real challenge, not just rebalancing weak stats.
- Reward totals scale with difficulty: trivial ~15, easy ~30, medium ~50, hard ~90, boss ~150+. Recovery quests feel soft and restful.`

// buildSuggestionPrompt renders the user's current state as the model's input.
func (s *Service) buildSuggestionPrompt() (string, error) {
	dash, err := s.GetDashboard()
	if err != nil {
		return "", err
	}
	weekly, err := s.store.WeeklyXPByAttribute(s.userID, time.Now().Add(-7*24*time.Hour))
	if err != nil {
		return "", err
	}
	journal, err := s.store.ListJournal(s.userID, 3)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "Character: %s, overall level %d.\n", dash.Character.Name, dash.Character.Level)
	fmt.Fprintf(&b, "Streak: %d days (best %d). Completed today: %d/%d.\n\n",
		dash.Streak.Current, dash.Streak.Longest, dash.DailyProgress.CompletedToday, dash.DailyProgress.Goal)

	b.WriteString("Attributes (level, total XP, XP earned in last 7 days):\n")
	for _, a := range dash.Attributes {
		fmt.Fprintf(&b, "- %s (key=%s): Lv%d, %d XP total, %d XP this week\n", a.Name, a.Key, a.Level, a.TotalXP, weekly[a.Key])
	}

	b.WriteString("\nActive quests right now — do NOT duplicate or reword these; suggest different actions:\n")
	if len(dash.TodayQuests) == 0 {
		b.WriteString("- (none)\n")
	}
	for _, q := range dash.TodayQuests {
		fmt.Fprintf(&b, "- %q [%s]\n", q.Title, q.Type)
	}

	if len(journal) > 0 {
		b.WriteString("\nRecent reflections (mood/energy out of 10):\n")
		for _, j := range journal {
			note := j.Notes
			if len(note) > 140 {
				note = note[:140] + "…"
			}
			fmt.Fprintf(&b, "- mood %d, energy %d: %s\n", j.Mood, j.Energy, note)
		}
	}

	b.WriteString("\nSuggest 2-4 quests as specified.")
	return b.String(), nil
}

// extractJSONObject returns the substring from the first '{' to the last '}',
// tolerating any stray prose or code fences around the model's JSON.
func extractJSONObject(s string) string {
	start := strings.IndexByte(s, '{')
	end := strings.LastIndexByte(s, '}')
	if start >= 0 && end > start {
		return s[start : end+1]
	}
	return s
}

func orFallback(s, fallback string) string {
	if strings.TrimSpace(s) == "" {
		return fallback
	}
	return s
}

// AcceptSuggestion turns a pending suggestion into a real quest and marks it accepted.
func (s *Service) AcceptSuggestion(id int64) (models.Quest, error) {
	sug, err := s.store.GetSuggestion(s.userID, id)
	if err != nil {
		return models.Quest{}, ErrNotFound
	}
	if sug.Status != "pending" {
		return models.Quest{}, validationErr("suggestion already %s", sug.Status)
	}
	in := sug.SuggestedQuest
	if err := s.validateQuestInput(&in); err != nil {
		return models.Quest{}, err
	}
	quest, err := s.store.AcceptSuggestion(s.userID, id, in)
	if err != nil {
		switch {
		case errors.Is(err, db.ErrNotFound):
			return models.Quest{}, ErrNotFound
		case errors.Is(err, db.ErrSuggestionNotPending):
			return models.Quest{}, validationErr("suggestion already resolved")
		default:
			return models.Quest{}, err
		}
	}
	return quest, nil
}

// DismissSuggestion marks a pending suggestion dismissed.
func (s *Service) DismissSuggestion(id int64) (models.AgentSuggestion, error) {
	sug, err := s.store.GetSuggestion(s.userID, id)
	if err != nil {
		return models.AgentSuggestion{}, ErrNotFound
	}
	if sug.Status != "pending" {
		return models.AgentSuggestion{}, validationErr("suggestion already %s", sug.Status)
	}
	if err := s.store.ResolveSuggestion(s.userID, id, "dismissed", nil); err != nil {
		return models.AgentSuggestion{}, err
	}
	return s.store.GetSuggestion(s.userID, id)
}
