import { useEffect, useState } from "react";
import { Bot, Check, Download, RefreshCw, Sparkles, Unplug } from "lucide-react";
import {
  useSuggestions,
  useGenerateSuggestions,
  useAcceptSuggestion,
  useDismissSuggestion,
  useOpenAIStatus,
  useConnectOpenAI,
  useImportCodex,
  useDisconnectOpenAI,
} from "../lib/queries";
import { SuggestionCard } from "../components/SuggestionCard";
import { Btn, EmptyState, SectionTitle, Spinner } from "../components/ui";
import { pushToast } from "../lib/toast";

export function SuggestionsPage() {
  const [connecting, setConnecting] = useState(false);
  const { data: status, isLoading: statusLoading } = useOpenAIStatus(connecting);
  const connected = !!status?.connected;

  const { data: suggestions, isLoading } = useSuggestions();
  const generate = useGenerateSuggestions();
  const accept = useAcceptSuggestion();
  const dismiss = useDismissSuggestion();

  const pending = suggestions?.filter((s) => s.status === "pending") ?? [];
  const resolved = suggestions?.filter((s) => s.status !== "pending") ?? [];
  const busy = accept.isPending || dismiss.isPending;

  // Stop polling + celebrate once the OAuth round-trip lands.
  useEffect(() => {
    if (connecting && connected) {
      setConnecting(false);
      pushToast(`Connected to ChatGPT${status?.email ? ` as ${status.email}` : ""}`, "success");
    }
  }, [connecting, connected, status?.email]);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 font-display text-xl font-bold tracking-tight text-ink">
            <Bot size={20} style={{ color: "#b18bff" }} /> AI Coach
          </h1>
          <p className="text-sm text-faint">Suggestions are generated by your own ChatGPT model.</p>
        </div>
        {connected && (
          <Btn
            variant="primary"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
            data-testid="generate-suggestions"
          >
            <RefreshCw size={15} className={generate.isPending ? "animate-spin" : ""} /> Generate
          </Btn>
        )}
      </div>

      {statusLoading ? (
        <Spinner />
      ) : !connected ? (
        <ConnectCard connecting={connecting} setConnecting={setConnecting} />
      ) : (
        <>
          <ConnectedBar email={status?.email} model={status?.model} />

          {isLoading ? (
            <Spinner />
          ) : (
            <>
              <section>
                <SectionTitle hint="Accept to turn into a real quest.">Pending</SectionTitle>
                {pending.length === 0 ? (
                  <EmptyState
                    icon={<Sparkles size={22} />}
                    title="No suggestions yet"
                    hint="Hit Generate — your ChatGPT model will analyze your progress and propose quests."
                  />
                ) : (
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {pending.map((s, i) => (
                      <SuggestionCard
                        key={s.id}
                        suggestion={s}
                        index={i}
                        busy={busy}
                        onAccept={(id) =>
                          accept.mutate(id, {
                            onSuccess: (q) => pushToast(`Added quest: ${q.title}`, "success"),
                          })
                        }
                        onDismiss={(id) => dismiss.mutate(id)}
                      />
                    ))}
                  </div>
                )}
              </section>

              {resolved.length > 0 && (
                <section>
                  <SectionTitle hint="Accepted or dismissed.">History</SectionTitle>
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {resolved.map((s, i) => (
                      <SuggestionCard key={s.id} suggestion={s} index={i} />
                    ))}
                  </div>
                </section>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}

function ConnectCard({
  connecting,
  setConnecting,
}: {
  connecting: boolean;
  setConnecting: (v: boolean) => void;
}) {
  const connect = useConnectOpenAI();
  const importCodex = useImportCodex();

  const startConnect = () =>
    connect.mutate(undefined, {
      onSuccess: (res) => {
        setConnecting(true);
        window.open(res.auth_url, "_blank", "noopener,noreferrer");
      },
    });

  return (
    <div className="hud-panel clip-corner relative overflow-hidden p-6 text-center">
      <div
        className="pointer-events-none absolute -right-10 -top-16 h-56 w-56 rounded-full"
        style={{ background: "radial-gradient(circle, rgba(52,208,255,0.16), transparent 70%)" }}
      />
      <div
        className="relative mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full"
        style={{ background: "rgba(177,139,255,0.14)", color: "#b18bff" }}
      >
        <Sparkles size={22} />
      </div>
      <h2 className="relative font-display text-lg font-bold text-ink">Connect your ChatGPT account</h2>
      <p className="relative mx-auto mt-1 max-w-md text-sm text-muted">
        edi's AI coach runs on <strong className="text-ink">your own</strong> ChatGPT Plus/Pro subscription —
        no API key, no extra cost. Sign in once to unlock personalized quest suggestions.
      </p>

      <div className="relative mt-5 flex flex-col items-center justify-center gap-2 sm:flex-row">
        <Btn variant="primary" disabled={connecting || connect.isPending} onClick={startConnect} data-testid="connect-openai">
          {connecting ? (
            <>
              <RefreshCw size={15} className="animate-spin" /> Waiting for sign-in…
            </>
          ) : (
            <>
              <Sparkles size={15} /> Connect ChatGPT account
            </>
          )}
        </Btn>
        <Btn
          variant="ghost"
          disabled={importCodex.isPending}
          onClick={() => importCodex.mutate()}
          data-testid="import-codex"
        >
          <Download size={15} /> Import from Codex CLI
        </Btn>
      </div>
      <p className="relative mt-3 text-[11px] text-faint">
        A browser tab opens at auth.openai.com; after signing in it returns automatically. Already use the
        Codex CLI? Import its session instantly.
      </p>
    </div>
  );
}

function ConnectedBar({ email, model }: { email?: string; model?: string }) {
  const disconnect = useDisconnectOpenAI();
  return (
    <div className="flex items-center justify-between gap-3 rounded-xl border border-edge bg-white/[0.02] px-4 py-2.5">
      <div className="flex items-center gap-2 text-sm">
        <span className="grid h-6 w-6 place-items-center rounded-full" style={{ background: "rgba(62,229,148,0.16)", color: "#3ee594" }}>
          <Check size={13} />
        </span>
        <span className="text-ink">{email || "ChatGPT connected"}</span>
        {model && <span className="tabnum text-[11px] text-faint">· {model}</span>}
      </div>
      <Btn variant="soft" disabled={disconnect.isPending} onClick={() => disconnect.mutate()} data-testid="disconnect-openai">
        <Unplug size={14} /> Disconnect
      </Btn>
    </div>
  );
}
