import { useEffect, useState } from "react";
import { Bot, Check, Download, RefreshCw, Sparkles, Unplug } from "lucide-react";
import {
  useSuggestions,
  useGenerateSuggestions,
  useAcceptSuggestion,
  useDismissSuggestion,
  useOpenAIStatus,
  useConnectOpenAI,
  useImportCodex,
  useDisconnectOpenAI,
  useSetOpenAIConfig,
  useOpenAIModels,
} from "../lib/queries";
import { SuggestionCard } from "../components/SuggestionCard";
import { Btn, EmptyState, SectionTitle, Spinner } from "../components/ui";
import { pushToast } from "../lib/toast";
import type { OpenAIStatus } from "../lib/types";

// Reasoning-effort tiers (the ChatGPT backend accepts only gpt-5.5, so depth is
// the meaningful knob). Fastest → deepest.
const EFFORT_META: Record<string, { label: string; hint: string }> = {
  none: { label: "Instant", hint: "No reasoning — fastest" },
  low: { label: "Fast", hint: "Light reasoning" },
  medium: { label: "Balanced", hint: "Default" },
  high: { label: "Deep", hint: "More reasoning" },
  xhigh: { label: "Max", hint: "Deepest, slowest" },
};

export function SuggestionsPage() {
  const [connecting, setConnecting] = useState(false);
  const { data: status, isLoading: statusLoading } = useOpenAIStatus(connecting);
  const connected = !!status?.connected;

  const { data: suggestions, isLoading } = useSuggestions();
  const generate = useGenerateSuggestions();
  const accept = useAcceptSuggestion();
  const dismiss = useDismissSuggestion();

  const pending = suggestions?.filter((s) => s.status === "pending") ?? [];
  const resolved = suggestions?.filter((s) => s.status !== "pending") ?? [];
  const busy = accept.isPending || dismiss.isPending;

  // Stop polling + celebrate once the OAuth round-trip lands.
  useEffect(() => {
    if (connecting && connected) {
      setConnecting(false);
      pushToast(`Connected to ChatGPT${status?.email ? ` as ${status.email}` : ""}`, "success");
    }
  }, [connecting, connected, status?.email]);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 font-display text-xl font-bold tracking-tight text-ink">
            <Bot size={20} style={{ color: "#b18bff" }} /> AI Coach
          </h1>
          <p className="text-sm text-faint">Suggestions are generated by your own ChatGPT model.</p>
        </div>
        {connected && (
          <Btn
            variant="primary"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
            data-testid="generate-suggestions"
          >
            <RefreshCw size={15} className={generate.isPending ? "animate-spin" : ""} /> Generate
          </Btn>
        )}
      </div>

      {statusLoading ? (
        <Spinner />
      ) : !connected ? (
        <ConnectCard connecting={connecting} setConnecting={setConnecting} />
      ) : (
        <>
          {status && <ConnectedBar status={status} />}

          {isLoading ? (
            <Spinner />
          ) : (
            <>
              <section>
                <SectionTitle hint="Accept to turn into a real quest.">Pending</SectionTitle>
                {pending.length === 0 ? (
                  <EmptyState
                    icon={<Sparkles size={22} />}
                    title="No suggestions yet"
                    hint="Hit Generate — your ChatGPT model will analyze your progress and propose quests."
                  />
                ) : (
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {pending.map((s, i) => (
                      <SuggestionCard
                        key={s.id}
                        suggestion={s}
                        index={i}
                        busy={busy}
                        onAccept={(id) =>
                          accept.mutate(id, {
                            onSuccess: (q) => pushToast(`Added quest: ${q.title}`, "success"),
                          })
                        }
                        onDismiss={(id) => dismiss.mutate(id)}
                      />
                    ))}
                  </div>
                )}
              </section>

              {resolved.length > 0 && (
                <section>
                  <SectionTitle hint="Accepted or dismissed.">History</SectionTitle>
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {resolved.map((s, i) => (
                      <SuggestionCard key={s.id} suggestion={s} index={i} />
                    ))}
                  </div>
                </section>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}

function ConnectCard({
  connecting,
  setConnecting,
}: {
  connecting: boolean;
  setConnecting: (v: boolean) => void;
}) {
  const connect = useConnectOpenAI();
  const importCodex = useImportCodex();

  const startConnect = () =>
    connect.mutate(undefined, {
      onSuccess: (res) => {
        setConnecting(true);
        window.open(res.auth_url, "_blank", "noopener,noreferrer");
      },
    });

  return (
    <div className="hud-panel clip-corner relative overflow-hidden p-6 text-center">
      <div
        className="pointer-events-none absolute -right-10 -top-16 h-56 w-56 rounded-full"
        style={{ background: "radial-gradient(circle, rgba(52,208,255,0.16), transparent 70%)" }}
      />
      <div
        className="relative mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full"
        style={{ background: "rgba(177,139,255,0.14)", color: "#b18bff" }}
      >
        <Sparkles size={22} />
      </div>
      <h2 className="relative font-display text-lg font-bold text-ink">Connect your ChatGPT account</h2>
      <p className="relative mx-auto mt-1 max-w-md text-sm text-muted">
        edi's AI coach runs on <strong className="text-ink">your own</strong> ChatGPT Plus/Pro subscription —
        no API key, no extra cost. Sign in once to unlock personalized quest suggestions.
      </p>

      <div className="relative mt-5 flex flex-col items-center justify-center gap-2 sm:flex-row">
        <Btn variant="primary" disabled={connecting || connect.isPending} onClick={startConnect} data-testid="connect-openai">
          {connecting ? (
            <>
              <RefreshCw size={15} className="animate-spin" /> Waiting for sign-in…
            </>
          ) : (
            <>
              <Sparkles size={15} /> Connect ChatGPT account
            </>
          )}
        </Btn>
        <Btn
          variant="ghost"
          disabled={importCodex.isPending}
          onClick={() => importCodex.mutate()}
          data-testid="import-codex"
        >
          <Download size={15} /> Import from Codex CLI
        </Btn>
      </div>
      <p className="relative mt-3 text-[11px] text-faint">
        A browser tab opens at auth.openai.com; after signing in it returns automatically. Already use the
        Codex CLI? Import its session instantly.
      </p>
    </div>
  );
}

function ConnectedBar({ status }: { status: OpenAIStatus }) {
  const disconnect = useDisconnectOpenAI();
  const setConfig = useSetOpenAIConfig();
  const { data: models } = useOpenAIModels(true);

  const currentModel = status.model ?? "";
  const selected = models?.find((m) => m.slug === currentModel);
  // Effort choices come from the selected model when known, else the status list.
  const effortOptions = selected?.efforts ?? status.effort_options ?? ["low", "medium", "high", "xhigh"];
  const currentEffort = status.effort ?? "medium";

  const changeModel = (slug: string) => {
    const m = models?.find((x) => x.slug === slug);
    // If the new model doesn't support the current effort, fall back to its default.
    const effort = m && !m.efforts.includes(currentEffort) ? m.default_effort || m.efforts[0] : undefined;
    setConfig.mutate(
      { model: slug, ...(effort ? { effort } : {}) },
      { onSuccess: () => pushToast(`Model set to ${m?.display_name ?? slug}`, "success") },
    );
  };

  return (
    <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-3 rounded-xl border border-edge bg-white/[0.02] px-4 py-2.5">
      <div className="flex items-center gap-2 text-sm">
        <span className="grid h-6 w-6 place-items-center rounded-full" style={{ background: "rgba(62,229,148,0.16)", color: "#3ee594" }}>
          <Check size={13} />
        </span>
        <span className="text-ink">{status.email || "ChatGPT connected"}</span>
      </div>

      <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
        {/* Model dropdown (populated from the account's available models) */}
        <label className="flex items-center gap-1.5">
          <span className="hidden text-[11px] text-faint sm:inline">Model</span>
          <select
            value={currentModel}
            disabled={setConfig.isPending || !models}
            onChange={(e) => changeModel(e.target.value)}
            data-testid="model-select"
            className="rounded-lg border border-edge bg-void/60 px-2 py-1 text-xs text-ink focus:border-[var(--color-gold)] focus:outline-none"
          >
            {!models && <option>{currentModel || "…"}</option>}
            {models?.map((m) => (
              <option key={m.slug} value={m.slug}>
                {m.display_name}
              </option>
            ))}
          </select>
        </label>

        {/* Reasoning-effort segmented control (per the selected model) */}
        <div className="flex items-center gap-1.5">
          <span className="hidden text-[11px] text-faint sm:inline">Reasoning</span>
          <div className="flex rounded-lg border border-edge bg-void/40 p-0.5" role="group" aria-label="Reasoning effort">
            {effortOptions.map((e) => {
              const meta = EFFORT_META[e] ?? { label: e, hint: "" };
              const active = e === currentEffort;
              return (
                <button
                  key={e}
                  title={meta.hint}
                  disabled={setConfig.isPending}
                  onClick={() =>
                    setConfig.mutate(
                      { effort: e },
                      { onSuccess: () => pushToast(`Reasoning set to ${meta.label}`, "success") },
                    )
                  }
                  data-testid={`effort-${e}`}
                  className="rounded-md px-2 py-1 text-[11px] font-medium transition-colors"
                  style={{
                    background: active ? "rgba(177,139,255,0.18)" : "transparent",
                    color: active ? "#c4a8ff" : "var(--color-faint)",
                  }}
                >
                  {meta.label}
                </button>
              );
            })}
          </div>
        </div>

        <Btn variant="soft" disabled={disconnect.isPending} onClick={() => disconnect.mutate()} data-testid="disconnect-openai">
          <Unplug size={14} /> Disconnect
        </Btn>
      </div>
    </div>
  );
}
