import { useEffect, useState } from "react";
import { Bot, Check, Download, RefreshCw, Send, Sparkles, Unplug } from "lucide-react";
import {
  useSuggestions,
  useGenerateSuggestions,
  useAcceptSuggestion,
  useDismissSuggestion,
  useOpenAIStatus,
  useCompleteOpenAIConnect,
  useConnectOpenAI,
  useImportCodex,
  useDisconnectOpenAI,
  useSetOpenAIConfig,
  useOpenAIModels,
  useTelegramPairCode,
  useTelegramStatus,
  useTelegramUnlink,
} from "../lib/queries";
import { SuggestionCard } from "../components/SuggestionCard";
import { Btn, EmptyState, SectionTitle, Spinner } from "../components/ui";
import { pushToast } from "../lib/toast";
import type { OpenAIStatus } from "../lib/types";

// Reasoning-effort tiers, fastest → deepest. Which tiers show comes from the
// selected model (gpt-5.6 adds "max"; sol/terra also "ultra").
const EFFORT_META: Record<string, { label: string; hint: string }> = {
  none: { label: "Instant", hint: "No reasoning — fastest" },
  low: { label: "Fast", hint: "Light reasoning" },
  medium: { label: "Balanced", hint: "Default" },
  high: { label: "Deep", hint: "More reasoning" },
  xhigh: { label: "Deeper", hint: "Extra reasoning, slower" },
  max: { label: "Max", hint: "Maximum reasoning — slowest" },
  ultra: { label: "Ultra", hint: "Max reasoning + task delegation" },
};

export function SuggestionsPage() {
  const [connecting, setConnecting] = useState(false);
  const { data: status, isLoading: statusLoading } = useOpenAIStatus(connecting);
  const connected = !!status?.connected;

  const { data: suggestions, isLoading } = useSuggestions();
  const generate = useGenerateSuggestions();
  const accept = useAcceptSuggestion();
  const dismiss = useDismissSuggestion();

  const pending = suggestions?.filter((s) => s.status === "pending") ?? [];
  const resolved = suggestions?.filter((s) => s.status !== "pending") ?? [];
  const busy = accept.isPending || dismiss.isPending;

  // Stop polling + celebrate once the OAuth round-trip lands.
  useEffect(() => {
    if (connecting && connected) {
      setConnecting(false);
      pushToast(`Connected to ChatGPT${status?.email ? ` as ${status.email}` : ""}`, "success");
    }
  }, [connecting, connected, status?.email]);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 font-display text-xl font-bold tracking-tight text-ink">
            <Bot size={20} style={{ color: "#b98aff" }} /> AI Coach
          </h1>
          <p className="text-sm text-faint">Suggestions are generated by your own ChatGPT model.</p>
        </div>
        {connected && (
          <Btn
            variant="primary"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
            data-testid="generate-suggestions"
          >
            <RefreshCw size={15} className={generate.isPending ? "animate-spin" : ""} /> Generate
          </Btn>
        )}
      </div>

      {statusLoading ? (
        <Spinner />
      ) : !connected ? (
        <ConnectCard connecting={connecting} setConnecting={setConnecting} />
      ) : (
        <>
          {status && <ConnectedBar status={status} />}

          {isLoading ? (
            <Spinner />
          ) : (
            <>
              <section>
                <SectionTitle hint="Accept to turn into a real quest.">Pending</SectionTitle>
                {pending.length === 0 ? (
                  <EmptyState
                    icon={<Sparkles size={22} />}
                    title="No suggestions yet"
                    hint="Hit Generate — your ChatGPT model will analyze your progress and propose quests."
                  />
                ) : (
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {pending.map((s, i) => (
                      <SuggestionCard
                        key={s.id}
                        suggestion={s}
                        index={i}
                        busy={busy}
                        onAccept={(id) =>
                          accept.mutate(id, {
                            onSuccess: (q) => pushToast(`Added quest: ${q.title}`, "success"),
                          })
                        }
                        onDismiss={(id) => dismiss.mutate(id)}
                      />
                    ))}
                  </div>
                )}
              </section>

              {resolved.length > 0 && (
                <section>
                  <SectionTitle hint="Accepted or dismissed.">History</SectionTitle>
                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {resolved.map((s, i) => (
                      <SuggestionCard key={s.id} suggestion={s} index={i} />
                    ))}
                  </div>
                </section>
              )}
            </>
          )}
        </>
      )}

      <TelegramCard />
    </div>
  );
}

function ConnectCard({
  connecting,
  setConnecting,
}: {
  connecting: boolean;
  setConnecting: (v: boolean) => void;
}) {
  const connect = useConnectOpenAI();
  const complete = useCompleteOpenAIConnect();
  const importCodex = useImportCodex();
  const [pasted, setPasted] = useState("");

  const startConnect = () =>
    connect.mutate(undefined, {
      onSuccess: (res) => {
        setConnecting(true);
        window.open(res.auth_url, "_blank", "noopener,noreferrer");
      },
    });

  const finishConnect = () =>
    complete.mutate(pasted, {
      onSuccess: () => setPasted(""),
    });

  return (
    <div className="hud-panel clip-corner relative overflow-hidden p-6 text-center">
      <div
        className="pointer-events-none absolute -right-10 -top-16 h-56 w-56 rounded-full"
        style={{ background: "radial-gradient(circle, rgba(52,208,255,0.16), transparent 70%)" }}
      />
      <div
        className="relative mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full"
        style={{ background: "rgba(185,138,255,0.14)", color: "#b98aff" }}
      >
        <Sparkles size={22} />
      </div>
      <h2 className="relative font-display text-lg font-bold text-ink">Connect your ChatGPT account</h2>
      <p className="relative mx-auto mt-1 max-w-md text-sm text-muted">
        edi's AI coach runs on <strong className="text-ink">your own</strong> ChatGPT Plus/Pro subscription —
        no API key, no extra cost. Sign in once to unlock personalized quest suggestions.
      </p>

      <div className="relative mt-5 flex flex-col items-center justify-center gap-2 sm:flex-row">
        <Btn variant="primary" disabled={connecting || connect.isPending} onClick={startConnect} data-testid="connect-openai">
          {connecting ? (
            <>
              <RefreshCw size={15} className="animate-spin" /> Waiting for sign-in…
            </>
          ) : (
            <>
              <Sparkles size={15} /> Connect ChatGPT account
            </>
          )}
        </Btn>
        <Btn
          variant="ghost"
          disabled={importCodex.isPending}
          onClick={() => importCodex.mutate()}
          data-testid="import-codex"
        >
          <Download size={15} /> Import from Codex CLI
        </Btn>
      </div>
      {connecting && (
        <div className="relative mx-auto mt-5 max-w-md space-y-2 text-left">
          <p className="text-[11px] leading-relaxed text-faint">
            After signing in, your browser lands on a <code className="text-muted">localhost:1455</code> page. If edi
            runs on this machine it connects by itself — otherwise that page shows an error (expected):{" "}
            <span className="text-muted">copy the full URL from the address bar</span> and paste it here.
          </p>
          <div className="flex gap-2">
            <input
              value={pasted}
              onChange={(e) => setPasted(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && pasted.trim() !== "" && finishConnect()}
              placeholder="http://localhost:1455/auth/callback?code=…"
              autoCapitalize="off"
              autoCorrect="off"
              spellCheck={false}
              data-testid="oauth-paste"
              className="min-w-0 flex-1 rounded-lg border border-edge bg-white/[0.03] px-3 py-2 text-xs text-ink placeholder:text-faint focus:border-[var(--color-gold)] focus:outline-none"
            />
            <Btn
              variant="primary"
              disabled={pasted.trim() === "" || complete.isPending}
              onClick={finishConnect}
              data-testid="oauth-paste-submit"
            >
              Finish
            </Btn>
          </div>
        </div>
      )}
      <p className="relative mt-3 text-[11px] text-faint">
        A browser tab opens at auth.openai.com. Already use the Codex CLI on this machine? Import its
        session instantly.
      </p>
    </div>
  );
}

function ConnectedBar({ status }: { status: OpenAIStatus }) {
  const disconnect = useDisconnectOpenAI();
  const setConfig = useSetOpenAIConfig();
  const { data: models } = useOpenAIModels(true);

  const currentModel = status.model ?? "";
  const selected = models?.find((m) => m.slug === currentModel);
  // Effort choices come from the selected model when known, else the status list.
  const effortOptions = selected?.efforts ?? status.effort_options ?? ["low", "medium", "high", "xhigh"];
  const currentEffort = status.effort ?? "medium";

  const changeModel = (slug: string) => {
    const m = models?.find((x) => x.slug === slug);
    // If the new model doesn't support the current effort, fall back to its default.
    const effort = m && !m.efforts.includes(currentEffort) ? m.default_effort || m.efforts[0] : undefined;
    setConfig.mutate(
      { model: slug, ...(effort ? { effort } : {}) },
      { onSuccess: () => pushToast(`Model set to ${m?.display_name ?? slug}`, "success") },
    );
  };

  return (
    <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-3 rounded-xl border border-edge bg-white/[0.02] px-4 py-2.5">
      <div className="flex items-center gap-2 text-sm">
        <span className="grid h-6 w-6 place-items-center rounded-full" style={{ background: "rgba(75,255,126,0.16)", color: "#4bff7e" }}>
          <Check size={13} />
        </span>
        <span className="text-ink">{status.email || "ChatGPT connected"}</span>
      </div>

      <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
        {/* Model dropdown (populated from the account's available models) */}
        <label className="flex items-center gap-1.5">
          <span className="hidden text-[11px] text-faint sm:inline">Model</span>
          <select
            value={currentModel}
            disabled={setConfig.isPending || !models}
            onChange={(e) => changeModel(e.target.value)}
            data-testid="model-select"
            className="rounded-lg border border-edge bg-void/60 px-2 py-1 text-xs text-ink focus:border-[var(--color-gold)] focus:outline-none"
          >
            {!models && <option>{currentModel || "…"}</option>}
            {models?.map((m) => (
              <option key={m.slug} value={m.slug}>
                {m.display_name}
              </option>
            ))}
          </select>
        </label>

        {/* Reasoning-effort segmented control (per the selected model) */}
        <div className="flex items-center gap-1.5">
          <span className="hidden text-[11px] text-faint sm:inline">Reasoning</span>
          <div className="flex rounded-lg border border-edge bg-void/40 p-0.5" role="group" aria-label="Reasoning effort">
            {effortOptions.map((e) => {
              const meta = EFFORT_META[e] ?? { label: e, hint: "" };
              const active = e === currentEffort;
              return (
                <button
                  key={e}
                  title={meta.hint}
                  disabled={setConfig.isPending}
                  onClick={() =>
                    setConfig.mutate(
                      { effort: e },
                      { onSuccess: () => pushToast(`Reasoning set to ${meta.label}`, "success") },
                    )
                  }
                  data-testid={`effort-${e}`}
                  className="rounded-md px-2 py-1 text-[11px] font-medium transition-colors"
                  style={{
                    background: active ? "rgba(185,138,255,0.18)" : "transparent",
                    color: active ? "#cbaaff" : "var(--color-faint)",
                  }}
                >
                  {meta.label}
                </button>
              );
            })}
          </div>
        </div>

        <Btn variant="soft" disabled={disconnect.isPending} onClick={() => disconnect.mutate()} data-testid="disconnect-openai">
          <Unplug size={14} /> Disconnect
        </Btn>
      </div>
    </div>
  );
}

// TelegramCard pairs this account with the Telegram bot: pushes (briefing,
// nudge) and chat commands (/status, /done). Hidden when the server has no
// bot configured. The pair code is shown once and burns on use.
function TelegramCard() {
  const { data: tg, refetch } = useTelegramStatus();
  const pair = useTelegramPairCode();
  const unlink = useTelegramUnlink();
  const [code, setCode] = useState<{ code: string; bot: string } | null>(null);

  // The status flips to linked once the user sends the code in Telegram —
  // poll briefly while a code is showing.
  useEffect(() => {
    if (!code) return;
    const t = setInterval(() => refetch(), 3000);
    return () => clearInterval(t);
  }, [code, refetch]);
  useEffect(() => {
    if (tg?.linked && code) {
      setCode(null);
      pushToast("Telegram linked", "success");
    }
  }, [tg?.linked, code]);

  if (!tg?.configured) return null;

  return (
    <div className="hud-panel flex flex-wrap items-center justify-between gap-3 p-4">
      <div className="min-w-0">
        <div className="flex items-center gap-2 text-sm font-medium text-ink">
          <Send size={15} style={{ color: "#34d0ff" }} /> Telegram
          {tg.linked && (
            <span className="rounded px-1.5 py-0.5 text-[10px] uppercase" style={{ background: "rgba(75,255,126,0.14)", color: "var(--color-phos)" }}>
              linked
            </span>
          )}
        </div>
        <p className="mt-0.5 text-xs text-faint">
          {tg.linked
            ? "Morning briefing, evening nudge, and /done from your pocket."
            : "Get briefings + complete quests from chat. Link your account to the bot."}
        </p>
        {code && (
          <div className="mt-2 space-y-1">
            <p className="text-xs text-muted">
              Send this to the bot (expires in 10 min): <code className="tabnum text-ink" data-testid="tg-code">/pair {code.code}</code>
            </p>
            <a
              href={`https://t.me/${code.bot}?start=${code.code}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block text-xs underline"
              style={{ color: "#34d0ff" }}
            >
              …or tap to open @{code.bot} and press Start
            </a>
          </div>
        )}
      </div>
      {tg.linked ? (
        <Btn variant="ghost" disabled={unlink.isPending} onClick={() => unlink.mutate()} data-testid="tg-unlink">
          <Unplug size={14} /> Unlink
        </Btn>
      ) : (
        <Btn
          variant="primary"
          disabled={pair.isPending}
          onClick={() => pair.mutate(undefined, { onSuccess: (r) => setCode({ code: r.code, bot: r.bot_username }) })}
          data-testid="tg-pair"
        >
          <Send size={14} /> Link Telegram
        </Btn>
      )}
    </div>
  );
}
