-- Consolidated PostgreSQL schema (replaces the SQLite migrations 001–007 from
-- the single-user era; the engine switch and the multi-tenant columns landed
-- together). Conventions:
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY — "by default" (not "always") so
--     a data restore from the SQLite era can insert explicit ids; reset the
--     sequences with setval() after any such restore.
--   * timestamptz everywhere — the store passes/scans time.Time directly.
--     Local-day math (streaks, decay, daily XP) happens in Go, honoring TZ.
--   * JSON payloads (attribute_rewards, suggested_quest, tool data) stay TEXT;
--     they are opaque to SQL and (un)marshaled at the store boundary.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    -- Multi-tenant auth: SHA-256 hex of the user's bearer token. NULL = the
    -- user cannot authenticate (dev fallback user, or token revoked).
    token_hash TEXT,
    is_admin   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX idx_users_token_hash ON users(token_hash) WHERE token_hash IS NOT NULL;

CREATE TABLE attributes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    key        TEXT NOT NULL,
    name       TEXT NOT NULL,
    total_xp   BIGINT NOT NULL DEFAULT 0,
    peak_xp    BIGINT NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL,
    UNIQUE(user_id, key)
);
CREATE INDEX idx_attributes_user ON attributes(user_id);

CREATE TABLE quests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id),
    title                TEXT NOT NULL,
    description          TEXT NOT NULL DEFAULT '',
    type                 TEXT NOT NULL DEFAULT 'daily',      -- daily, weekly, main, side, boss, recovery
    difficulty           TEXT NOT NULL DEFAULT 'easy',       -- trivial, easy, medium, hard, boss
    status               TEXT NOT NULL DEFAULT 'active',     -- active, completed, skipped, archived
    attribute_rewards    TEXT NOT NULL DEFAULT '{}',         -- JSON: {"strength":40,"discipline":10}
    skip_count           BIGINT NOT NULL DEFAULT 0,
    source_suggestion_id BIGINT,
    created_at           timestamptz NOT NULL,
    completed_at         timestamptz,
    due_date             timestamptz
);
CREATE INDEX idx_quests_user_status ON quests(user_id, status);
CREATE INDEX idx_quests_type ON quests(user_id, type);

CREATE TABLE quest_subtasks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id),
    quest_id          BIGINT NOT NULL REFERENCES quests(id),
    title             TEXT NOT NULL,
    attribute_rewards TEXT NOT NULL DEFAULT '{}',  -- JSON bonus, e.g. {"health":15}
    done              INTEGER NOT NULL DEFAULT 0,  -- 0/1 (toggled via 1 - done)
    created_at        timestamptz NOT NULL
);
CREATE INDEX idx_subtasks_quest ON quest_subtasks(quest_id);
CREATE INDEX idx_subtasks_user ON quest_subtasks(user_id);

CREATE TABLE quest_completions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    quest_id     BIGINT NOT NULL REFERENCES quests(id),
    xp_awarded   BIGINT NOT NULL DEFAULT 0,
    completed_at timestamptz NOT NULL
);
CREATE INDEX idx_completions_user ON quest_completions(user_id, completed_at);

CREATE TABLE xp_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    attribute_key TEXT NOT NULL,
    amount        BIGINT NOT NULL,
    source        TEXT NOT NULL,           -- quest, subtask, tool, journal, decay, seed, manual
    source_id     BIGINT,                  -- e.g. quest id
    note          TEXT NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL
);
CREATE INDEX idx_xp_events_user ON xp_events(user_id, created_at);
CREATE INDEX idx_xp_events_attr ON xp_events(user_id, attribute_key, created_at);

CREATE TABLE streaks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES users(id),
    current_count    INTEGER NOT NULL DEFAULT 0,
    longest_count    INTEGER NOT NULL DEFAULT 0,
    last_active_date TEXT                        -- local YYYY-MM-DD, compared in Go
);

CREATE TABLE journal_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    mood       INTEGER NOT NULL,    -- 1..10
    energy     INTEGER NOT NULL,    -- 1..10
    notes      TEXT NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL
);
CREATE INDEX idx_journal_user ON journal_entries(user_id, created_at);

CREATE TABLE agent_suggestions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id),
    type             TEXT NOT NULL,
    title            TEXT NOT NULL,
    reason           TEXT NOT NULL DEFAULT '',
    suggested_quest  TEXT NOT NULL DEFAULT '{}',     -- JSON quest template
    status           TEXT NOT NULL DEFAULT 'pending',-- pending, accepted, dismissed
    created_quest_id BIGINT,
    source_quest_id  BIGINT,
    created_at       timestamptz NOT NULL,
    resolved_at      timestamptz
);
CREATE INDEX idx_suggestions_user_status ON agent_suggestions(user_id, status);

CREATE TABLE openai_credentials (
    user_id       BIGINT PRIMARY KEY REFERENCES users(id),
    access_token  TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    id_token      TEXT NOT NULL DEFAULT '',
    account_id    TEXT NOT NULL DEFAULT '',
    email         TEXT NOT NULL DEFAULT '',
    expires_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

CREATE TABLE app_settings (
    user_id BIGINT NOT NULL REFERENCES users(id),
    key     TEXT NOT NULL,
    value   TEXT NOT NULL,
    PRIMARY KEY (user_id, key)
);

CREATE TABLE tool_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    tool_key    TEXT NOT NULL,
    data        TEXT NOT NULL DEFAULT '{}',   -- JSON, tool-specific
    summary     TEXT NOT NULL DEFAULT '',
    xp_awarded  BIGINT NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL
);
CREATE INDEX idx_tool_entries_user ON tool_entries(user_id, tool_key, created_at);

CREATE TABLE gold_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    amount       BIGINT NOT NULL,               -- + mint, - purchase
    source       TEXT NOT NULL,                 -- quest, subtask, tool, journal, purchase, ward, grant
    label        TEXT NOT NULL DEFAULT '',
    shop_item_id BIGINT,
    created_at   timestamptz NOT NULL
);
CREATE INDEX idx_gold_events_user ON gold_events(user_id, created_at);
CREATE INDEX idx_gold_events_source ON gold_events(user_id, source);

CREATE TABLE shop_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    name        TEXT NOT NULL,
    price       BIGINT NOT NULL,
    created_at  timestamptz NOT NULL,
    archived_at timestamptz                     -- archive, never delete
);
CREATE INDEX idx_shop_items_user ON shop_items(user_id, archived_at);

CREATE TABLE wards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    attribute_key TEXT NOT NULL,
    expires_at    timestamptz NOT NULL,
    created_at    timestamptz NOT NULL
);
CREATE INDEX idx_wards_user_attr ON wards(user_id, attribute_key, expires_at);
