-- Loot: items dropped by quest completions. The catalog (names, rarities,
-- effects) lives in code (internal/db/loot.go — the store owns drops the way
-- it owns XP); this table is the per-user inventory ledger.
CREATE TABLE user_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    item_key   TEXT NOT NULL,               -- catalog key
    rarity     TEXT NOT NULL,               -- common | uncommon | rare | epic | legendary
    source_id  BIGINT,                      -- quest id that dropped it
    created_at timestamptz NOT NULL
);
CREATE INDEX idx_user_items_user ON user_items(user_id, created_at);

-- Active temporal buffs (from buff-type loot): +XP% on an attribute (or all)
-- until local midnight. Applied as auditable 'buff' xp_events at completion.
CREATE TABLE user_buffs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    item_key      TEXT NOT NULL,
    attribute_key TEXT NOT NULL DEFAULT '', -- '' = all attributes
    percent       INTEGER NOT NULL,         -- e.g. 25 = +25% XP
    expires_at    timestamptz NOT NULL,
    created_at    timestamptz NOT NULL
);
CREATE INDEX idx_user_buffs_user ON user_buffs(user_id, expires_at);

-- Dropless-streak counter for the pity mechanic (guaranteed drop after N).
CREATE TABLE loot_pity (
    user_id  BIGINT PRIMARY KEY REFERENCES users(id),
    dropless INTEGER NOT NULL DEFAULT 0
);
