-- Achievements: the catalog (names, conditions, titles) lives in code
-- (services/achievements.go); this table records what each user has earned.
-- UNIQUE makes awarding idempotent (evaluation re-runs freely).
CREATE TABLE achievements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    key        TEXT NOT NULL,
    awarded_at timestamptz NOT NULL,
    UNIQUE(user_id, key)
);
CREATE INDEX idx_achievements_user ON achievements(user_id);
