-- Shared two-player quest boards. A shared quest is stored once per assignee
-- in quests so completion, recurring rollover, subtasks, XP, gold, and streaks
-- continue to use the existing per-user transactional paths. shared_quests
-- links those copies into one logical card on the board.

CREATE TABLE quest_boards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL
);

CREATE TABLE quest_board_members (
    board_id  BIGINT NOT NULL REFERENCES quest_boards(id),
    user_id   BIGINT NOT NULL UNIQUE REFERENCES users(id),
    joined_at timestamptz NOT NULL,
    PRIMARY KEY (board_id, user_id)
);
CREATE INDEX idx_quest_board_members_board ON quest_board_members(board_id);

CREATE TABLE quest_board_invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id    BIGINT NOT NULL REFERENCES quest_boards(id),
    code_hash   TEXT NOT NULL UNIQUE,
    created_by  BIGINT NOT NULL REFERENCES users(id),
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz
);
CREATE INDEX idx_quest_board_invites_board ON quest_board_invites(board_id);

CREATE TABLE shared_quests (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id   BIGINT NOT NULL REFERENCES quest_boards(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL
);
CREATE INDEX idx_shared_quests_board ON shared_quests(board_id);

ALTER TABLE quests ADD COLUMN shared_quest_id BIGINT REFERENCES shared_quests(id);
CREATE INDEX idx_quests_shared ON quests(shared_quest_id) WHERE shared_quest_id IS NOT NULL;
