-- Admin-minted onboarding invitations. The plaintext code is returned once;
-- only its SHA-256 hash is stored. Consumption and user creation happen in one
-- transaction so a concurrent double-submit can create at most one account.
CREATE TABLE account_invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash   TEXT NOT NULL UNIQUE,
    created_by  BIGINT NOT NULL REFERENCES users(id),
    created_at  timestamptz NOT NULL,
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    consumed_by BIGINT REFERENCES users(id)
);

CREATE INDEX idx_account_invites_active
    ON account_invites(expires_at)
    WHERE consumed_at IS NULL;
