-- Supplements tool: a personal daily stack. Each supplement taken awards a
-- small amount of XP; taking the whole active stack in one local day awards a
-- bonus once. Supplements are soft-deleted (archived_at) because intakes and
-- their xp_events reference them and the XP audit must survive removal.
CREATE TABLE supplements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    name        TEXT NOT NULL,
    dose        TEXT NOT NULL DEFAULT '',
    sort_order  INT  NOT NULL DEFAULT 0,
    archived_at timestamptz,
    created_at  timestamptz NOT NULL
);
CREATE INDEX idx_supplements_user ON supplements(user_id, archived_at, sort_order, id);
-- One active supplement per name per user (case-insensitive). The service
-- checks first for a friendly message; this makes concurrent adds safe.
CREATE UNIQUE INDEX idx_supplements_user_name_active ON supplements(user_id, lower(name)) WHERE archived_at IS NULL;

-- taken_on is the Go-computed local calendar day (YYYY-MM-DD) — never SQL
-- zone math. UNIQUE is the backstop for the in-tx "already taken today" check.
CREATE TABLE supplement_intakes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    supplement_id BIGINT NOT NULL REFERENCES supplements(id),
    taken_on      TEXT NOT NULL,
    xp_awarded    BIGINT NOT NULL DEFAULT 0,
    bonus         BOOLEAN NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL,
    UNIQUE(user_id, supplement_id, taken_on)
);
CREATE INDEX idx_supplement_intakes_user_day ON supplement_intakes(user_id, taken_on);
