-- Active quest mode (ADHD loop, phase 1). Additive only.
-- One row per "run" of a quest: Start opens it, Stop/Complete/expiry closes
-- it. Sessions are presence during the action — they never write XP
-- (cosmetic ticks only); completion stays the award.
CREATE TABLE IF NOT EXISTS quest_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    quest_id   BIGINT NOT NULL REFERENCES quests(id),
    started_at timestamptz NOT NULL,
    ended_at   timestamptz,
    reason     TEXT NOT NULL DEFAULT '',   -- '' while running; stopped | completed | switched | expired
    note       TEXT NOT NULL DEFAULT ''    -- the "next physical action" captured at Stop
);
CREATE INDEX IF NOT EXISTS idx_quest_sessions_active ON quest_sessions(user_id, ended_at);

-- The quest's standing "next physical action" (survives across sessions,
-- cleared on completion). Shown on the card and in the running panel.
ALTER TABLE quests ADD COLUMN IF NOT EXISTS resume_note TEXT NOT NULL DEFAULT '';
