-- ADHD loop, phase 2 (additive only).
-- If-then triggers (implementation intentions): "when <trigger>, I do <quest>"
-- with an optional clock anchor the scheduler fires a one-line Start prompt at.
ALTER TABLE quests ADD COLUMN IF NOT EXISTS trigger_text TEXT NOT NULL DEFAULT '';
ALTER TABLE quests ADD COLUMN IF NOT EXISTS trigger_at   TEXT NOT NULL DEFAULT ''; -- HH:MM local, '' = no clock anchor

-- Story chapters: the narrator remembers. One row per narrated episode.
CREATE TABLE IF NOT EXISTS story_chapters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    number     INTEGER NOT NULL,
    text       TEXT NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_story_chapters_user ON story_chapters(user_id, id DESC);
