-- Cosmetics: gear for the hero, bought with gold. The catalog (keys, slots,
-- prices, looks) lives in code (internal/services/cosmetics.go); these
-- tables hold what a user owns and what they wear. Additive only.
CREATE TABLE cosmetic_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    item_key   TEXT NOT NULL,                -- catalog key
    created_at timestamptz NOT NULL,
    UNIQUE (user_id, item_key)               -- a piece is owned once, forever
);
CREATE INDEX idx_cosmetic_items_user ON cosmetic_items(user_id, created_at);

-- One equipped item per slot (head, body, weapon, offhand, back, aura, pet).
CREATE TABLE cosmetic_loadout (
    user_id    BIGINT NOT NULL REFERENCES users(id),
    slot       TEXT NOT NULL,
    item_key   TEXT NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (user_id, slot)
);
